---
title: Healthy Affordable Materials Project
url: http://hamp.siteleaf.net
timezone: UTC
collections:
  partners:
    title: Partners
    output: false
  projects:
    title: Projects
    output: false
  news:
    title: News
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: partners
  values:
    image:
    link:
- scope:
    path: ''
    type: projects
  values:
    partner:
    image:
    link:
- scope:
    path: ''
    type: news
  values:
    partner:
    date:
    link:
permalink: pretty
