---
title: Healthy Affordable Materials Project
url: http://hamp.siteleaf.net
timezone: UTC
collections:
  news:
    title: News
    output: false
  partners:
    title: Partners
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: partners
  values:
    image: 
    link: 
- scope:
    path: ''
    type: projects
  values:
    partner: 
    image: 
    link: 
- scope:
    path: ''
    type: news
  values:
<<<<<<< HEAD
    partner:
    date:
    link:
=======
    partner: 
    link: 
>>>>>>> origin/master
permalink: pretty
