---
title: Healthy Affordable Materials Project
timezone: America/New_York
collections:
  board:
    title: Board
    output: false
    intro: The Healthy Affordable Materials Project is a four-part collaborative supported
      by a grant from [The JPB Foundation](http://jpbfoundation.org/) and guided by
      a board of expert advisors.
    advisoryCommittee: "+ Joseph Allen, Director of the Healthy Buildings program
      at the Harvard Center for Health and the Global Environment  \n\n+ Michael Bodaken,
      President of National Housing Trust  \n\nLisa Britton, Director of Sales & Marketing
      and Sustainability Champion at Industrial Louvers, Inc.  \n\nErin Christensen
      Ishizaki, Partner and co-director of Urban Placemaking at Mithun  \n\nRolf Halden,
      Ph.D., P.E., Professor in the School of Sustainable Engineering and the Built
      Environment at Arizona State University  \n\nChunrong Jia, PhD, Associate Professor,
      Division of Epidemiology, Biostatistics, and Environmental Health at University
      of Memphis  \n\nJohn McManus, editorial and digital content director for the
      Residential Group at Hanley Wood  \n\nHilary Noll, Enterprise Rose Architectural
      Fellow working with First Community Housing in San Jose, CA.  \n\nSeandra Pope,
      President & CEO of Rooted Consulting Group  \n\nFran Wagstaff, National Affordable
      Housing Expert and an innovator who redefined the way affordable housing is
      perceived, designed, developed and financed  "
  posts:
    title: News
    output: true
  partners:
    title: Partners
    output: false
  projects:
    title: Projects
    output: false
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: partners
  values:
    image: 
    fullName: 
    link: 
- scope:
    path: ''
    type: board
  values:
    link: 
    boardPosition: 
- scope:
    path: ''
    type: projects
  values:
    partner: 
    image: 
    link: 
- scope:
    path: ''
    type: posts
  values:
    partner: 
    link: 
- scope:
    path: ''
    type: slides
  values:
    image: 
    color-1: 
    color-2: 
    textureImage: 
permalink: pretty
description: The Healthy Affordable Materials Project—a four-partner collaborative
  funded by The JPB Foundation—unites manufacturers, developers, research scientists,
  designers, and advocates in a push to replace existing materials with safer, more
  affordable alternatives.
image: "/uploads/hamp-lockup.png"
