---
title: Healthy Affordable Materials Project
timezone: America/New_York
collections:
  board:
    title: Board
    output: false
    intro: The Healthy Affordable Materials Project is a four-part collaborative supported
      by a grant from [The JPB Foundation](http://jpbfoundation.org/) and guided by
      a board of expert advisors.
    advisoryCommittee: "Michael Bodaken, President of Bodaken & Associates\n<br/><br/>\nLisa
      Britton, Director of Sales & Marketing and Sustainability Champion at Industrial
      Louvers, Inc.  \n<br/><br/>\nRolf Halden, Ph.D., P.E., Professor in the School
      of Sustainable Engineering and the Built Environment at Arizona State University
      \ \n<br/><br/>\nSeandra Pope, President & CEO of Rooted Consulting Group  \n<br/><br/>\nJess
      Blanch, Design Associate and Enterprise Rose Architectural Fellow, Capitol Hill
      Housing\n<br/><br/>\nCatherine Bobenhausen, Senior Consultant at Colden Corporation\n<br/><br/>\nJoanna
      Frank, President and CEO of Center for Active Design\n<br/><br/>\nDr. Maida
      Galvez, Associate Professor of Environmental Medicine, Public Health, and Pediatrics,
      Icahn School of Medicine at Mount Sinai\n<br/><br/>\nGretta Goldenman, Director
      at Millieu Ltd\n<br/><br/>\nJean Hansen, FIIDA, LEED Fellow, CID, EDAC, AAHID,
      Sustainable Principal, HDR\n<br/><br/>\nMartin Mulvihill, Managing Partner and
      Co-Founder at Safer Made, and Senior Advisor and Board Member for Berkeley Center
      for Green Chemistry\n<br/><br/>\nBecky Schaaf, Senior Vice President, Energy
      at SAHF\n<br/><br/>\nJoel Towers, Executive Dean of Parsons School of Design
      at The New School and Director of Tishman Environmental Design Center\n"
  posts:
    title: News
    output: true
  partners:
    title: Partners
    output: false
  projects:
    title: Projects
    output: false
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: partners
  values:
    image: 
    fullName: 
    link: 
- scope:
    path: ''
    type: board
  values:
    link: 
    boardPosition: 
- scope:
    path: ''
    type: projects
  values:
    partner: 
    image: 
    link: 
- scope:
    path: ''
    type: posts
  values:
    partner: 
    link: 
- scope:
    path: ''
    type: slides
  values:
    image: 
    color-1: 
    color-2: 
    textureImage: 
permalink: pretty
description: The Healthy Affordable Materials Project—a four-partner collaborative
  funded by The JPB Foundation—unites manufacturers, developers, research scientists,
  designers, and advocates in a push to replace existing materials with safer, more
  affordable alternatives.
image: "/uploads/hamp-lockup.png"
