---
title: Healthy Affordable Materials Project
url: http://hamp.siteleaf.net
timezone: America/New_York
collections:
  board:
    title: Board
    output: false
    body: The Healthy Affordable Materials Project is a four-part collaborative supported
      by a grant from [The JPB Foundation](http://jpbfoundation.org/) and guided by
      a board of expert advisors.
    comingSoon: A full list of advisors is forthcoming.
  posts:
    title: News
    output: true
  partners:
    title: Partners
    output: false
  projects:
    title: Projects
    output: false
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: partners
  values:
    image:
    fullName:
    link:
- scope:
    path: ''
    type: board
  values:
    link:
    boardPosition:
- scope:
    path: ''
    type: projects
  values:
    partner:
    image:
    link:
- scope:
    path: ''
    type: posts
  values:
    partner:
    link:
- scope:
    path: ''
    type: slides
  values:
    image:
    color-1:
    color-2:
    textureImage:
permalink: pretty
description: The Healthy Affordable Materials Project—a four-partner collaborative
  funded by The JPB Foundation—unites manufacturers, developers, research scientists,
  designers, and advocates in a push to replace existing materials with safer, more
  affordable alternatives.
image: "/uploads/hamp-lockup.png"
